//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AusterlitzDbContext : DbContext
    {
        public AusterlitzDbContext()
            : base("name=AusterlitzDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<REF_ArmyList> REF_ArmyList { get; set; }
        public virtual DbSet<REF_Population> REF_Population { get; set; }
        public virtual DbSet<REF_ProductionSites> REF_ProductionSites { get; set; }
        public virtual DbSet<REF_Ships> REF_Ships { get; set; }
        public virtual DbSet<REF_States> REF_States { get; set; }
        public virtual DbSet<REF_Terrain> REF_Terrain { get; set; }
        public virtual DbSet<REF_UnitWeightsRates> REF_UnitWeightsRates { get; set; }
        public virtual DbSet<TR_BaggageTrains> TR_BaggageTrains { get; set; }
        public virtual DbSet<TR_Barracks> TR_Barracks { get; set; }
        public virtual DbSet<TR_Brigades> TR_Brigades { get; set; }
        public virtual DbSet<TR_Commanders> TR_Commanders { get; set; }
        public virtual DbSet<TR_MerchantShips> TR_MerchantShips { get; set; }
        public virtual DbSet<TR_Spies> TR_Spies { get; set; }
        public virtual DbSet<TR_StateRelationships> TR_StateRelationships { get; set; }
        public virtual DbSet<TR_TradingPortsAndCities> TR_TradingPortsAndCities { get; set; }
        public virtual DbSet<TR_Warehouses> TR_Warehouses { get; set; }
        public virtual DbSet<TR_Warships> TR_Warships { get; set; }
        public virtual DbSet<TS_00TurnDetails> TS_00TurnDetails { get; set; }
        public virtual DbSet<TS_01TransferGoods> TS_01TransferGoods { get; set; }
        public virtual DbSet<TS_02DemolishItems> TS_02DemolishItems { get; set; }
        public virtual DbSet<TS_03SetUpBrigades> TS_03SetUpBrigades { get; set; }
        public virtual DbSet<TS_04SetUpAdditionalBrigades> TS_04SetUpAdditionalBrigades { get; set; }
        public virtual DbSet<TS_05IncreaseHeadcount> TS_05IncreaseHeadcount { get; set; }
        public virtual DbSet<TS_06IncreaseBrigadeXP> TS_06IncreaseBrigadeXP { get; set; }
        public virtual DbSet<TS_07ExchangeBattalions> TS_07ExchangeBattalions { get; set; }
        public virtual DbSet<TS_08MergeBattalions> TS_08MergeBattalions { get; set; }
        public virtual DbSet<TS_09RepairShips_BaggageTrains> TS_09RepairShips_BaggageTrains { get; set; }
        public virtual DbSet<TS_10BuildShips> TS_10BuildShips { get; set; }
        public virtual DbSet<TS_11BuildBaggageTrain> TS_11BuildBaggageTrain { get; set; }
        public virtual DbSet<TS_12IncreasePopulationDensity> TS_12IncreasePopulationDensity { get; set; }
        public virtual DbSet<TS_13BuildProductionSites> TS_13BuildProductionSites { get; set; }
        public virtual DbSet<TS_14FormFederations> TS_14FormFederations { get; set; }
        public virtual DbSet<TS_15CoastalDefence> TS_15CoastalDefence { get; set; }
        public virtual DbSet<TS_16SeaBlockade> TS_16SeaBlockade { get; set; }
        public virtual DbSet<TS_17TradeAndLoading1> TS_17TradeAndLoading1 { get; set; }
        public virtual DbSet<TS_18Movement> TS_18Movement { get; set; }
        public virtual DbSet<TS_19TradeAndLoading2> TS_19TradeAndLoading2 { get; set; }
        public virtual DbSet<TS_20Boarding> TS_20Boarding { get; set; }
        public virtual DbSet<TS_21HandOverTerritory> TS_21HandOverTerritory { get; set; }
        public virtual DbSet<TS_22ChangeNames> TS_22ChangeNames { get; set; }
        public virtual DbSet<TS_23ChangeStateRelationships> TS_23ChangeStateRelationships { get; set; }
        public virtual DbSet<TR_MapCoordinates> TR_MapCoordinates { get; set; }
        public virtual DbSet<REF_PoliticalMapCoordinates> REF_PoliticalMapCoordinates { get; set; }
    }
}
