//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_Terrain_Factor
    {
        public string TerrainId { get; set; }
        public string TroopType { get; set; }
        public Nullable<int> TF { get; set; }
        public string TerrainTypeId { get; set; }
    }
}
