//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_ArmyList
    {
        public int ItemNo { get; set; }
        public string State { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int Cost { get; set; }
        public int EcPtsPer25 { get; set; }
        public int EF { get; set; }
        public int HC { get; set; }
        public int LR { get; set; }
        public int RG { get; set; }
        public int SimMP { get; set; }
        public int MP { get; set; }
        public string Formation { get; set; }
        public bool Allow_Co { get; set; }
        public bool Allow_Li { get; set; }
        public bool Allow_Sk { get; set; }
        public bool Allow_Sq { get; set; }
        public bool IsColonial { get; set; }
        public string TroopSpecification { get; set; }
        public bool IsCavalry { get; set; }
    }
}
