//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_ProductionSites
    {
        public int SiteTypeNo { get; set; }
        public string Terrain { get; set; }
        public string SiteType { get; set; }
        public string Symbol { get; set; }
        public string SecondarySymbol { get; set; }
        public int Cost { get; set; }
        public int Maintenance { get; set; }
        public int MinPopulation { get; set; }
        public int MaxPopulation { get; set; }
        public string ProductionType { get; set; }
        public int MinProduction { get; set; }
        public int MaxProduction { get; set; }
        public Nullable<int> MinProductionColonial { get; set; }
        public string MaxProductionColonial { get; set; }
        public string BonusSymbol { get; set; }
        public Nullable<int> BonusPercentage { get; set; }
        public int CitizensRequired { get; set; }
    }
}
