//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_Population
    {
        public int Density { get; set; }
        public int TotalCitizens { get; set; }
        public int ExtraCitizensRequired { get; set; }
        public string StoneOrWood { get; set; }
        public int GoodAmount { get; set; }
    }
}
