//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_UnitWeightsRates
    {
        public int WeightOfItem { get; set; }
        public string ItemType { get; set; }
        public Nullable<int> GoodsFactors { get; set; }
    }
}
