//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_Ships
    {
        public int Type { get; set; }
        public string Name { get; set; }
        public int Wood { get; set; }
        public int EcPts { get; set; }
        public int Textiles { get; set; }
        public int Citizens { get; set; }
        public int Cost { get; set; }
        public int Maintenance { get; set; }
        public int LoadCapacity { get; set; }
        public int MovementFactor { get; set; }
        public Nullable<int> ShipClass { get; set; }
    }
}
