//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Brigades
    {
        public int ItemNo { get; set; }
        public string TurnId { get; set; }
        public string Name { get; set; }
        public string CoordinateX_OrState { get; set; }
        public string CoordinateY_OrFleet { get; set; }
        public int MP { get; set; }
        public int Federation { get; set; }
        public string Batt1Type { get; set; }
        public Nullable<int> Batt1EF { get; set; }
        public Nullable<int> Batt1Size { get; set; }
        public string Batt2Type { get; set; }
        public Nullable<int> Batt2EF { get; set; }
        public Nullable<int> Batt2Size { get; set; }
        public string Batt3Type { get; set; }
        public Nullable<int> Batt3EF { get; set; }
        public Nullable<int> Batt3Size { get; set; }
        public string Batt4Type { get; set; }
        public Nullable<int> Batt4EF { get; set; }
        public Nullable<int> Batt4Size { get; set; }
        public string Batt5Type { get; set; }
        public Nullable<int> Batt5EF { get; set; }
        public Nullable<int> Batt5Size { get; set; }
        public string Batt6Type { get; set; }
        public Nullable<int> Batt6EF { get; set; }
        public Nullable<int> Batt6Size { get; set; }
        public string Batt7Type { get; set; }
        public Nullable<int> Batt7EF { get; set; }
        public Nullable<int> Batt7Size { get; set; }
    }
}
