//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Barracks
    {
        public int ItemNo { get; set; }
        public string TurnId { get; set; }
        public string Type { get; set; }
        public int Money { get; set; }
        public int Citizens { get; set; }
        public int EcPts { get; set; }
        public int Wood { get; set; }
        public int Horses { get; set; }
        public int Text { get; set; }
        public int FortressSize { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    }
}
