//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Commanders
    {
        public int ItemNo { get; set; }
        public string TurnId { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public Nullable<int> Boarded { get; set; }
        public int Federation { get; set; }
        public int MP { get; set; }
        public int CommandCapacity { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    }
}
