//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_EconomyComputedSummary
    {
        public string TurnId { get; set; }
        public string Sphere { get; set; }
        public Nullable<System.DateTime> ComputedAtUtc { get; set; }
        public Nullable<int> ComputedVersion { get; set; }
        public long StartingRevenueLd { get; set; }
        public long ArmyMaintLd { get; set; }
        public long NavyMaintLd { get; set; }
        public long ProductionMaintLd { get; set; }
        public long ArmyBuildingLd { get; set; }
        public long ArmyTrainingLd { get; set; }
        public long NavyBuildRepairLd { get; set; }
        public long ProductionBuildLd { get; set; }
        public long LdInBarracks { get; set; }
        public long BuildFundsAvailableLd { get; set; }
        public long TransferToEuropeLd { get; set; }
        public long TransferFromEuropeLd { get; set; }
        public long TransferToCaribbeanLd { get; set; }
        public long TransferFromCaribbeanLd { get; set; }
        public long TransferToIndiaLd { get; set; }
        public long TransferFromIndiaLd { get; set; }
        public long DirectSellingLd { get; set; }
        public long DirectBuyingLd { get; set; }
        public long TaxesLd { get; set; }
        public long LdProduction { get; set; }
        public long ProjectedNextMonthLd { get; set; }
    }
}
