//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_EconomySummary
    {
        public string TurnId { get; set; }
        public int ProductionMaintenanceLd { get; set; }
        public int EuropeMaintenanceWorkers { get; set; }
        public int CaribbeanMaintenanceWorkers { get; set; }
        public int IndiaMaintenanceWorkers { get; set; }
        public int CommanderPayLd { get; set; }
        public int BrigadePayLd { get; set; }
        public int NavyMaintenanceLd { get; set; }
        public int NavyMaintenanceMarines { get; set; }
        public int BarracksCount { get; set; }
        public int FactoriesCount { get; set; }
        public int WeavingMillsCount { get; set; }
        public int MintsCount { get; set; }
        public int EstatesCount { get; set; }
        public int SheepFarmsCount { get; set; }
        public int HorseFarmsCount { get; set; }
        public int LumberCampsCount { get; set; }
        public int QuarriesCount { get; set; }
        public int MinesCount { get; set; }
        public int VineyardsCount { get; set; }
        public int FreeAreasCount { get; set; }
    }
}
