//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TR_Epidemics
    {
        [Key]
        [Column(Order = 0)]
        [StringLength(13)]
        public string TurnId { get; set; }

        [Key]
        [Column(Order = 1)]
        public int X { get; set; }

        [Key]
        [Column(Order = 2)]
        public int Y { get; set; }

        [Key]
        [Column(Order = 3)]
        [StringLength(1)]
        public string State { get; set; }
    }
}
