//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_MapCoordinates
    {
        public string TurnId { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public string State { get; set; }
        public string ProductionSite { get; set; }
        public string Population { get; set; }
    }
}
