//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Spies
    {
        public string TurnId { get; set; }
        public int ItemNo { get; set; }
        public int XCoordinate { get; set; }
        public int YCoordinate { get; set; }
        public int FederationNo { get; set; }
        public string Reports { get; set; }
        public string FortressSize { get; set; }
    }
}
