//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;

    public partial class TR_SeaBattles
    {
        public string TurnId { get; set; }
        public int SeaBattleNo { get; set; }
        public string GroupAName { get; set; }
        public string GroupBName { get; set; }
        public string StateA { get; set; }
        public string StateB { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public string WinnerGroup { get; set; }
        public string WinnerText { get; set; }
        public int GroupATonnageBegin { get; set; }
        public int GroupATonnageEnd { get; set; }
        public decimal GroupATonnageLossPct { get; set; }
        public int GroupAMarinesBegin { get; set; }
        public int GroupAMarinesEnd { get; set; }
        public decimal GroupAMarinesLossPct { get; set; }
        public decimal GroupAAverageLossPct { get; set; }
        public int GroupBTonnageBegin { get; set; }
        public int GroupBTonnageEnd { get; set; }
        public decimal GroupBTonnageLossPct { get; set; }
        public int GroupBMarinesBegin { get; set; }
        public int GroupBMarinesEnd { get; set; }
        public decimal GroupBMarinesLossPct { get; set; }
        public decimal GroupBAverageLossPct { get; set; }
    }
}
