//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;

    public partial class TR_SeaBattleBoardingActions
    {
        public int SeaBattleBoardingActionId { get; set; }
        public string TurnId { get; set; }
        public int SeaBattleNo { get; set; }
        public int RoundNo { get; set; }
        public int ActionNo { get; set; }
        public int AttackerShipNo { get; set; }
        public string AttackerGroupSide { get; set; }
        public int AttackerMarines { get; set; }
        public string AttackerOutcome { get; set; }
        public int DefenderShipNo { get; set; }
        public string DefenderGroupSide { get; set; }
        public int DefenderMarines { get; set; }
        public string DefenderOutcome { get; set; }
    }
}
