//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;

    public partial class TR_SeaBattleLongRangeActions
    {
        public int SeaBattleLongRangeActionId { get; set; }
        public string TurnId { get; set; }
        public int SeaBattleNo { get; set; }
        public int RoundNo { get; set; }
        public string GroupSide { get; set; }
        public int ReportShipNo { get; set; }
        public int ShipType { get; set; }
        public int Tonnage { get; set; }
        public int Marines { get; set; }
        public int EnemyShipNo { get; set; }
    }
}
