//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;

    public partial class TR_SeaBattleShips
    {
        public int SeaBattleShipId { get; set; }
        public string TurnId { get; set; }
        public int SeaBattleNo { get; set; }
        public string GroupSide { get; set; }
        public string Phase { get; set; }
        public string ShipKind { get; set; }
        public Nullable<int> ReportShipNo { get; set; }
        public Nullable<int> FinalItemNo { get; set; }
        public Nullable<int> Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> Tonnage { get; set; }
        public Nullable<int> Marines { get; set; }
        public string Brigade { get; set; }
        public Nullable<int> ConditionPct { get; set; }
        public Nullable<int> Goods1 { get; set; }
        public Nullable<int> Goods2 { get; set; }
    }
}
