//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;

    public partial class TR_SeaBattleMerchantCaptures
    {
        public int SeaBattleMerchantCaptureId { get; set; }
        public string TurnId { get; set; }
        public int SeaBattleNo { get; set; }
        public int RoundNo { get; set; }
        public int CapturedShipNo { get; set; }
        public int CapturedByShipNo { get; set; }
    }
}
