//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TradingPortsAndCities
    {
        public string TurnId { get; set; }
        public int ItemNo { get; set; }
        public int XCoordinate { get; set; }
        public int YCoordinate { get; set; }
        public int Rate { get; set; }
        public int EctPts { get; set; }
        public int Food { get; set; }
        public int Stone { get; set; }
        public int Wood { get; set; }
        public int Ore { get; set; }
        public int Zinc { get; set; }
        public int Horses { get; set; }
        public int Text { get; set; }
        public int Wool { get; set; }
        public int Gold { get; set; }
        public int Wine { get; set; }
    }
}
