//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TurnCostSummary
    {
        public string TurnId { get; set; }
        public Nullable<decimal> ProdSites { get; set; }
        public Nullable<decimal> Commanders { get; set; }
        public Nullable<decimal> Brigades { get; set; }
        public Nullable<decimal> MerchantShips { get; set; }
        public Nullable<decimal> Warships { get; set; }
    }
}
