//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TurnOrderErrors
    {
        public int TurnOrderErrorId { get; set; }
        public string TurnId { get; set; }
        public short SectionNo { get; set; }
        public short OrderNo { get; set; }
        public short ErrorCode { get; set; }
        public string RawToken { get; set; }
    }
}
