//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Warships
    {
        public string TurnId { get; set; }
        public int ItemNo { get; set; }
        public int Type { get; set; }
        public int XCoordinate { get; set; }
        public int YCoordinate { get; set; }
        public int FleetNo { get; set; }
        public int MP { get; set; }
        public int Condition { get; set; }
        public int Age { get; set; }
        public int Marines { get; set; }
        public int Brigade1 { get; set; }
        public int Brigade2 { get; set; }
    }
}
