//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_01TransferGoods
    {
        public TS_01TransferGoods()
        {
            this.From = 0;
            this.To = 0;
            this.Louisdore = 0;
            this.Citizens = 0;
            this.EcPts = 0;
            this.Wood = 0;
            this.Horses = 0;
            this.Textiles = 0;
        }
    
        public string TurnId { get; set; }
        public int OrderNo { get; set; }
        public Nullable<int> From { get; set; }
        public Nullable<int> To { get; set; }
        public Nullable<int> Louisdore { get; set; }
        public Nullable<int> Citizens { get; set; }
        public Nullable<int> EcPts { get; set; }
        public Nullable<int> Wood { get; set; }
        public Nullable<int> Horses { get; set; }
        public Nullable<int> Textiles { get; set; }
    }
}
