//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_14FormFederations
    {
        public string TurnId { get; set; }
        public int OrderNo { get; set; }
        public int ItemNo { get; set; }
        public int Federation_Fleet { get; set; }
    }
}
