//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austerlitz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_16SeaBlockade
    {
        public string TurnId { get; set; }
        public int OrderNo { get; set; }
        public Nullable<int> FleetNo { get; set; }
        public string StateA_Or_Fleet0 { get; set; }
        public string StateB { get; set; }
        public string StateC { get; set; }
        public string StateD { get; set; }
        public string StateE { get; set; }
    }
}
