"use strict";

austerlitzModule.factory("economyConfigFactory", function () {
  var tradeEstimateGoodsConfig = [
    { cityKey: "ectPts", goodsFactor: 6 },
    { cityKey: "food", goodsFactor: 4 },
    { cityKey: "stone", goodsFactor: 1 },
    { cityKey: "wood", goodsFactor: 3 },
    { cityKey: "ore", goodsFactor: 30 },
    { cityKey: "zinc", goodsFactor: 45 },
    { cityKey: "horses", goodsFactor: 2 },
    { cityKey: "textiles", goodsFactor: 5 },
    { cityKey: "wool", goodsFactor: 2 },
    { cityKey: "gold", goodsFactor: 35 },
    { cityKey: "wine", goodsFactor: 8 },
  ];
  var goodsFactorByKey = {};
  tradeEstimateGoodsConfig.forEach(function (item) {
    goodsFactorByKey[item.cityKey] = item.goodsFactor;
  });

  return {
    sphereByTab: {
      europe: { minX: 1, maxX: 80, minY: 1, maxY: 65 },
      caribbean: { minX: 1, maxX: 40, minY: 70, maxY: 99 },
      india: { minX: 51, maxX: 90, minY: 70, maxY: 99 },
    },
    economyTabs: { europe: true, caribbean: true, india: true },
    economyWarehouseNos: [1, 2, 3],
    economyComputedVersion: 2,
    resourceKeys: [
      "money",
      "citizens",
      "ecPts",
      "food",
      "stone",
      "wood",
      "ore",
      "zinc",
      "horses",
      "textiles",
      "wool",
      "gold",
      "wine",
    ],
    productionRowConfig: [
      { key: "barracks", label: "2. Barracks", siteTypeNo: 2 },
      { key: "factories", label: "4. Factories", siteTypeNo: 4 },
      { key: "weaving", label: "5. Weaving Mills", siteTypeNo: 5 },
      { key: "mints", label: "6. Mints", siteTypeNo: 6 },
      { key: "primeEstates", label: "7. Prime Estates", siteTypeNo: 7, prime: true },
      { key: "estates", label: "7. Estates", siteTypeNo: 7, prime: false },
      { key: "primeSheep", label: "8. Prime Sheep Farm", siteTypeNo: 8, prime: true },
      { key: "sheep", label: "8. Sheep Farm", siteTypeNo: 8, prime: false },
      { key: "primeHorse", label: "9. Prime Horse Farm", siteTypeNo: 9, prime: true },
      { key: "horse", label: "9. Horse Farm", siteTypeNo: 9, prime: false },
      { key: "lumber", label: "10. Lumber Camp", siteTypeNo: 10 },
      { key: "quarries", label: "11. Quarries", siteTypeNo: 11 },
      { key: "goldMine", label: "12. Gold Mine", siteTypeNo: 12, productionType: "gold" },
      { key: "oreMine", label: "12. Ore Mine", siteTypeNo: 12, productionType: "ore" },
      { key: "zincMine", label: "12. Zinc Mine", siteTypeNo: 12, productionType: "zinc" },
      { key: "vineyards", label: "13. Vineyards", siteTypeNo: 13 },
    ],
    productionResourceColumnsByRowKey: {
      factories: { ecPts: true, wood: true, ore: true, zinc: true, textiles: true },
      weaving: { textiles: true },
      mints: { gold: true },
      primeEstates: { food: true },
      estates: { food: true },
      primeSheep: { wool: true },
      sheep: { wool: true },
      primeHorse: { horses: true },
      horse: { horses: true },
      lumber: { wood: true },
      quarries: { stone: true },
      goldMine: { gold: true },
      oreMine: { ore: true },
      zincMine: { zinc: true },
      vineyards: { wine: true },
    },
    tradeEstimateGoodsConfig: tradeEstimateGoodsConfig,
    tradeGoodsIdToKey: {
      13: "ectPts",
      16: "food",
      18: "stone",
      19: "wood",
      20: "ore",
      21: "zinc",
      22: "horses",
      23: "textiles",
      24: "wool",
      29: "gold",
      30: "wine",
    },
    goodsFactorByKey: goodsFactorByKey,
    populationCitizensByDensity: {
      1: 4000,
      2: 10000,
      3: 20000,
      4: 40000,
      5: 60000,
      6: 90000,
      7: 120000,
      8: 160000,
      9: 200000,
    },
    mintGoldPerSiteCap: 20,
  };
});
